<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="suite1" duration-ms="443" started-at="2020-02-16T19:50:22 IST" finished-at="2020-02-16T19:50:23 IST">
    <groups>
    </groups>
    <test name="testtest" duration-ms="443" started-at="2020-02-16T19:50:22 IST" finished-at="2020-02-16T19:50:23 IST">
      <class name="practice.excelexample">
        <test-method status="FAIL" signature="testcase1(java.lang.String, java.lang.String)[pri:0, instance:practice.excelexample@5ae63ade]" name="testcase1" duration-ms="0" started-at="2020-02-16T19:50:23 IST" data-provider="exceldata" finished-at="2020-02-16T19:50:23 IST">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Data Provider public org.apache.poi.ss.usermodel.Cell practice.excelexample.getdatafromprovider() throws java.lang.Exception must return either Object[][] or Object[] or Iterator<Object[]> or Iterator<Object>, not interface org.apache.poi.ss.usermodel.Cell]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Data Provider public org.apache.poi.ss.usermodel.Cell practice.excelexample.getdatafromprovider() throws java.lang.Exception must return either Object[][] or Object[] or Iterator<Object[]> or Iterator<Object>, not interface org.apache.poi.ss.usermodel.Cell
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:175)
at org.testng.internal.Parameters.handleParameters(Parameters.java:820)
at org.testng.internal.Parameters.handleParameters(Parameters.java:762)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:60)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:39)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:771)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase1 -->
      </class> <!-- practice.excelexample -->
    </test> <!-- testtest -->
  </suite> <!-- suite1 -->
</testng-results>
